##### Fresh Install for Ubuntu 24.04 ####

# Stop Docker Service
- name: Stop Docker service
  service:
    name: docker
    state: stopped
    enabled: yes
  become: yes
  become_method: sudo
  ignore_errors: yes

# System update / upgrade
- name: Apt update and dist-upgrade
  apt:
    update_cache: yes
    upgrade: dist
  become: yes
  become_method: sudo

# Install time sync tool (ntpdate binary)
- name: Install ntpdate
  apt:
    name: ntpdate
    state: present
  become: yes
  become_method: sudo
  ignore_errors: yes

# Install required packages
- name: Install required packages
  apt:
    name:
      - rsync
      - python3-pip
    state: present
    update_cache: yes
  become: yes
  become_method: sudo

- name: Install base packages
  apt:
    name:
      - rsync
      - python3-pip
      - python3-boto
      - python3-docker
      - python3-lxml
      - unzip
    state: present
    update_cache: yes
  become: yes
  become_method: sudo
  
# ---------- AWS CLI v2 via bundled installer ----------

- name: Download AWS CLI v2 installer
  get_url:
    url: https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip
    dest: /tmp/awscliv2.zip
    mode: '0644'
  become: yes
  become_method: sudo

- name: Unpack AWS CLI v2 installer
  unarchive:
    src: /tmp/awscliv2.zip
    dest: /tmp/
    remote_src: yes
  become: yes
  become_method: sudo

- name: Install AWS CLI v2
  command: /tmp/aws/install --bin-dir /usr/local/bin --install-dir /usr/local/aws-cli
  args:
    creates: /usr/local/aws-cli/v2/current/bin/aws
  become: yes
  become_method: sudo

# ---------- End AWS CLI section ----------

# firewalld (optional, only if 'firewalld' var is defined)
- name: Apt install firewalld
  apt:
    name: firewalld
    state: present
  become: yes
  become_method: sudo
  when: "firewalld is defined"

- name: Boot firewalld
  shell: systemctl enable firewalld && systemctl start firewalld
  become: yes
  become_method: sudo
  when: "firewalld is defined"

# Ensure valid server time (ecs pull fails if time is wrong)
- name: Update server time
  shell: ntpdate -u ntp.ubuntu.com
  become: yes
  become_method: sudo
  ignore_errors: yes

# Start Docker Service
- name: Start Docker service
  service:
    name: docker
    state: started
    enabled: yes
  become: yes
  become_method: sudo

# Without regular container cleanup, the server will run out of disk space
- name: Docker System Prune (disk clean up)
  shell: docker system prune -a -f
  become: yes
  become_method: sudo
  ignore_errors: yes
